- name: Install Request Middleware
      run: pip install requests

    - name: Execute Python Cookie Exchange Fetch
      env:
        NSE_RAW_COOKIE: ${{ secrets.NSE_COOKIE }}
      run: python fetch.py
