# .github/workflows/update_prices.yml
name: Update Stock Prices Daily

on:
  schedule:
    # Runs Monday to Friday at 4:30 PM IST (11:00 AM UTC)
    - cron: '0 11 * * 1-5'
  workflow_dispatch: # Allows you to update prices manually inside GitHub anytime

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install jugaad-data

      - name: Fetch prices
        run: python fetch_prices.py

      - name: Commit and Push update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add prices.json
          git commit -m "Auto-update latest prices [skip ci]" || echo "No changes to commit"
          git push
